name: API Testing Pipeline ðŸš€

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
    - name: Baixando o cÃ³digo (Checkout)
      uses: actions/checkout@v4

    - name: Instalando Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Instalando DependÃªncias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executando Testes de API
      run: pytest -v -s